# Generated by Django 4.2 on 2023-04-16 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["createdAt"],
            },
        ),
        migrations.AddConstraint(
            model_name="taskmodel",
            constraint=models.UniqueConstraint(fields=("title",), name="unique_title"),
        ),
    ]
